name: Deploy Angular app to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Set S3 credentials in environment.prod.ts
        run: |
          cat <<EOF > src/environments/environment.prod.ts
          export const environment = {
            production: true,
            s3: {
              accessKeyId: '${{ secrets.AWS_ACCESS_KEY_ID }}',
              secretAccessKey: '${{ secrets.AWS_SECRET_ACCESS_KEY }}',
              region: '${{ secrets.AWS_REGION }}',
              bucketName: '${{ secrets.S3_BUCKET_NAME }}'
            }
          };
          EOF

      - name: Build Angular app for GitHub Pages
        run: npm run build:ghpages

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx angular-cli-ghpages --dir=dist/s3-browser --no-silent --repo=https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
